// Code generated by mockery v1.0.0. DO NOT EDIT.

package types

import mock "github.com/stretchr/testify/mock"

// MockRateProvider is an autogenerated mock type for the RateProvider type
type MockRateProvider struct {
	mock.Mock
}

// GetRate provides a mock function with given fields: pair
func (_m *MockRateProvider) GetRate(pair CurrencyPair) (CurrencyRate, error) {
	ret := _m.Called(pair)

	var r0 CurrencyRate
	if rf, ok := ret.Get(0).(func(CurrencyPair) CurrencyRate); ok {
		r0 = rf(pair)
	} else {
		r0 = ret.Get(0).(CurrencyRate)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(CurrencyPair) error); ok {
		r1 = rf(pair)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Name provides a mock function with given fields:
func (_m *MockRateProvider) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
